name: Build Docker Image & Push to Docker.io

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit-resume:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/streamlit-resume:latest

      #- name: Build and push Docker image to Docker Hub
        # uses: docker/build-push-action@v4
        # with:
        #   context: .  # Path to the Dockerfile and build context
        #   file: Dockerfile  # Path to the Dockerfile
        #   push: true
        #   tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit-resume:${{ github.sha }}
        # env:
        #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
